### ISSUE TITLE
Can't run sbt run

### ISSUE THREAD

**Issue by gergelyke** [m2mIO/mqtt-loadtest#1]
Hi,

sorry, if it is dummy question, I am not a scala/java pro.

When I try to run `sbt run`, it downloads the deps, but got this error:

```
error: error while loading CharSequence, class file '/Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/rt.jar(java/lang/CharSequence.class)' is broken
(bad constant pool tag 18 at byte 10)
```

any clues what should I do?

thanks,

g

**Comment by TheRyanBurke** [comment]
This project has been archived and will no longer be supported by 2lemetry/Amazon Web Services.
